### ISSUE TITLE
Join Now button is not redirecting us to any form.

### ISSUE THREAD

**Issue by mohitk30** [mohitk30/Alumni-Cell-Web#1]
Join Now Button on home page is not redirecting us to the required form . it should redirect us to a google form of link 
[Form Link](https://docs.google.com/forms/d/e/1FAIpQLScO_T_-_MHrGBBIA2XRtLdSx4I-Ynz0dJnwgT7odf10DJbW4w/viewform) in a new tab.

**Comment by ShreyanshRaj22** [comment]
Assign this issue to me.

**Comment by mohitk30** [comment]
okk start working on that and once it is done let us know @ShreyanshRaj22

**Comment by mohitk30** [comment]
Solved by @ShreyanshRaj22
