### ISSUE TITLE
Collapsing of alumni card whose image is not avilable

### ISSUE THREAD

**Issue by mohitk30** [mohitk30/Alumni-Cell-Web#2]
The cards of alumni on home page are collapsing because their image is not available in assets section, to solve this if alumni images are not available then show a demo image of person but the card should be their. 

So try alternate static image reference to all card which will be shown if image of alumni is not accessible.

**Comment by moulik10sharma** [comment]
Please assign this to me.

**Comment by mohitk30** [comment]
Resolved by @moulik10sharma
