### ISSUE TITLE
Number section shows only zeros

### ISSUE THREAD

**Issue by mohitk30** [mohitk30/Alumni-Cell-Web#3]
The section above the footer in home page show 0 every where it should show some hard codded data as of now . Later we will get this data from API's. As of now ad some number like `10+` or `100+` the number should be relatable to the entity shown.

**Comment by SunnyMaurya63** [comment]
Assign this issue to me

**Comment by mohitk30** [comment]
This issue is assigned to @SunnyMaurya63

**Comment by mohitk30** [comment]
again make a pull request with refactored code
@SunnyMaurya63

**Comment by mohitk30** [comment]
Resolved by @SunnyMaurya63
