### ISSUE TITLE
Empty blocks in upcoming events sections

### ISSUE THREAD

**Issue by mohitk30** [mohitk30/Alumni-Cell-Web#4]
In upcoming events section in home page  their are some empty blocks as of now no event is scheduled so it should show no event scheduled as of now . if future is their is any event it should show states, so comment that logic and add new logic that show  **No upcoming Events.**

**Comment by mohitk30** [comment]
Make sure you just comment the earlier logic do not remove that commented part.

**Comment by ksiddharth3107** [comment]
Assign this to me please.

**Comment by mohitk30** [comment]
solved by @ksiddharth3107
